version: "3.3"
services:
  node:
    image: "opendigitaleducation/node:16-alpine-pnpm"
    working_dir: /home/node/app
    network_mode: host
    volumes:
      - ./:/home/node/app
      - ~/.pnpm:/.pnpm
