#!/usr/bin/env groovy

pipeline {
  agent any
  stages {
    stage('Init') {
      steps {
        checkout scm
        sh 'cd frontend'
        sh './build.sh clean init'
      }
    }
    stage('Build') {
      steps {
        sh 'cd frontend'
        sh "./build.sh build"
      }
    }
    stage('Publish NPM') {
      steps {
        configFileProvider([configFile(fileId: '.npmrc-infra-front', variable: 'NPMRC')]) {
          sh 'cd frontend'
          sh "cp $NPMRC .npmrc"
          sh "./build.sh publishNPM"
        }
      }
    }
  }
}

