#!/usr/bin/env groovy

pipeline {
  agent any

  environment {
    TIPTAP_PRO_TOKEN = credentials('tiptap-pro-token')
  }

  stages {
    stage('Init') {
      steps {
        checkout scm
        sh 'cd frontend && ./build.sh clean init'
      }
    }
    stage('Build') {
      steps {
        sh "cd frontend && ./build.sh build"
      }
    }
    stage('Publish NPM') {
      steps {
        configFileProvider([configFile(fileId: '.npmrc-infra-front', variable: 'NPMRC')]) {
          sh "cd frontend && cp $NPMRC .npmrc"
          sh "cd frontend && ./build.sh publishNPM"
        }
      }
    }
  }
  post {
    cleanup {
      sh 'cd frontend && (docker-compose down || true)'
    }
  }
}

