GRANT USAGE ON SCHEMA explorer TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA explorer TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA explorer TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA explorer TO "apps";