GRANT USAGE ON SCHEMA explorer TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA explorer TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA explorer TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA explorer TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA explorer GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA explorer GRANT EXECUTE ON FUNCTIONS TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA explorer GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";